name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout

      - name: Setup Pages
        uses: actions/configure-pages

      - name: Deploy to GitHub Pages  
        uses: peaceiris/actions-gh-pages
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
